### ISSUE TITLE
[Bug]:  Test Containers 4.1.0 fail

### ISSUE THREAD

**Issue by jkerken** [testcontainers/testcontainers-dotnet#1589]
### Testcontainers version

4.1.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

8.0.409

### Docker version

```shell
Client:
 Version:           27.4.1
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        b9d17ea
 Built:             Tue Dec 17 15:44:45 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.4.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       c710b88
  Built:            Tue Dec 17 15:46:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.24
  GitCommit:        88bf19b2105c8b17560993bee28a01ddc2f97182
 runc:
  Version:          1.2.3
  GitCommit:        v1.2.3-0-g0d37cfd
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.3.1
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.2.1
  GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
```

### Docker info

```shell
Version:    27.4.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.3-0-g0d37cfd
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 5.15.0-1098-azure
 Operating System: Ubuntu 24.04.3 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.62GiB
 Name: agent-dind-h24fd-hcztr
 ID: e61d5882-255d-4e2e-aece-bbf44158206f
 Docker Root Dir: /home/rootless/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://harbor.harbor.svc.cluster.local/
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. Systemd is required to enable cgroups in rootless-mode.
```

### What happened?

After upgrading from 4.0.0 to 4.1.0 (or latest) we get the following error when test containers wants to start containers:

`/_/src/Docker.DotNet/DockerClient.cs(492): error test failed: ---- Docker.DotNet.DockerApiException : Docker API responded with status code=InternalServerError, response={"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"sysfs\" to rootfs at \"/sys\": mount src=sysfs, dst=/sys, dstFd=/proc/thread-self/fd/8, flags=0xe: operation not permitted: unknown"} 
`

### Relevant log output

```shell

```

### Additional information

This runs in an azure pipeline self hosted agent where docker is started rootless with the following supervisord config:

```
[program:dockerd]
command=/usr/local/bin/dockerd-rootless.sh
user=rootless
environment=HOME="/home/rootless",USER="rootless"
autorestart=true
stderr_logfile=/home/rootless/%(program_name)s_stderr.log
stdout_logfile=/home/rootless/%(program_name)s_stdout.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile_backups=0
```
We also have harbor docker.io registry mirror setup:
Content of `/home/rootless/.config/docker/daemon.json` : 

`{ "ip6tables": false, "registry-mirrors": ["https://harbor.harbor.svc.cluster.local"] }`

Following ENV vars are set:

DOCKER_HOST="unix:///run/user/1000/docker.sock"
DOCKER_CONFIG="/home/rootless/.config/docker"
TESTCONTAINERS_HOST_OVERRIDE="127.0.0.1"

**Comment by HofmeisterAn** [comment]
I don't think this is a bug in TC. A simple `docker run` would probably fail as well. Docker can't create or start the container at all.

> self hosted agent where docker is started rootless with the following supervisord config:

There seem to be quite a few customizations here. Based on the info you provided, I'd recommend updating your environment and making sure all components match properly.

Your host is running kernel version `5.15`, which belongs to older Ubuntu releases (like 22.04). But you're running 24.04, which uses a 6.x-series kernel. Please try using the official (Azure-optimized) kernel package for 24.04. My guess is that the containerized OS was upgraded, but the host running the container runtime wasn't.

```
 Kernel Version: 5.15.0-1098-azure
 Operating System: Ubuntu 24.04.3 LTS (containerized)
```

**Comment by jkerken** [comment]
@HofmeisterAn The pipeline is also pulling and running images as part of the pipeline itself. This works without a problem.

Also as mentioned with TestContainers 4.0.0 everything works. Then updating to any later version fails with this error.

The mismatch in version comes from the fact that we run the agents on AKS nodes which are still on Ubuntu 22 for now.

**Comment by HofmeisterAn** [comment]
The setup is way too complex, with too many customizations for me to provide much help here. I can only share that I've seen issues running containers on MS-hosted runners (GitHub or Azure) when certain kernel versions are involved (`5.15` with Ubuntu 24.04).

I looked at the changes in 4.1.0, and it's possible your setup is running into problems with: https://github.com/testcontainers/testcontainers-dotnet/pull/1313.

Could you try setting the `TESTCONTAINERS_RYUK_CONTAINER_PRIVILEGED` environment variable to `false` and see if that helps?

**Comment by HofmeisterAn** [comment]
@jkerken Did you manage to solve the issue? Can you please share the stack trace?

**Comment by HofmeisterAn** [comment]
I'll close this. If you need further assistance, let me know.

**Comment by jkerken** [comment]
@HofmeisterAn This was related to Ryuk probably the priviledged flag you mentioned.

We have now disabled ryuk completly since we dont need it on the build agents. Works now. Thanks for the support!
